server:
  port: 15555
spring:
  cloud:
    alicloud:
      access-key: 
      secret-key: 
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: kkc-picture
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: kkc-picture
